# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21276965c331729499add1dbdf66259713b29cce9deffa2f3a9e6c71115dad2cf57f8765946738402ceb8f3749baa10e2568c22fc733b1fbbf7ebec1fb496f6d

test:
  secret_key_base: 9153eadb7c27ff4ba3e4fe78b36faa4569b2f4c3aaf9731fa85a9d9e30054f80f4383e75b222d6d6a8c8a384c6ff23aceab50f5d7758f54b7a105855680d0944

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
